language: node_js
node_js:
  - "6"
branches:
  only:
    - master
    - gh-pages
cache:
  yarn: true
  directories:
    - "node_modules"
script: "yarn doc"
deploy:
  provider: pages
  skip_cleanup: false
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: doc
